version: "3.7"
services:

  caddy:
    image: caddy
    # restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./laravel:/srv
    ports:
      - "80:80"
      # - "443:443"
    depends_on:
      - app
    networks:
      - sije.harkema.xyz

  app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
      args:
        user: sije
        uid: 1000
    # image: sije.harkema.xyz
    # container_name: sije.harkema.xyz-app
    networks:
      - sije.harkema.xyz
    # restart: unless-stopped
    working_dir: /srv
    volumes:
      # Note to self: on permissions error this required a one-time: chmod -R g+w .
      - ./laravel:/srv
      # Thanks https://matthewsetter.com/setup-step-debugging-php-xdebug3-docker/
      - ./docker/laravel/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/laravel/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - "9000:9000"

  redis:
    image: redis:7.2-alpine
    networks:
      - sije.harkema.xyz


networks:
  sije.harkema.xyz:
    driver: bridge


volumes:
  caddy_data:
  caddy_config: